name: 'Deploy'

on:
  release:
    types:
      - published
  push:
    branches:
      - master
      - develop
      - 'dev/**'

jobs:
  surge:
    name: Surge deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - run: |
          domain=${{ secrets.SURGE_DOMAIN_STAGE }}
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun=${{ secrets.SURGE_DOMAIN }}
          fi
          touch .env

          echo SERVER_PUBLIC_URL=${{ secrets.SERVER_PUBLIC_URL }} >> .env
          echo FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }} >> .env
          echo GOOGLE_WEB_ID=${{ secrets.GOOGLE_WEB_ID }} >> .env
          echo GOOGLE_IOS_ID=${{ secrets.GOOGLE_IOS_ID }} >> .env
          echo GOOGLE_EXPO_ID=${{ secrets.GOOGLE_EXPO_ID }} >> .env

          yarn workspace @solve/client install
          yarn workspace @solve/client build:web
          cp -r ./packages/client/web-build/index.html ./packages/client/web-build/200.html
          yarn surge packages/client/web-build $domain --token ${{ secrets.SURGE_TOKEN }}
  heroku:
    name: Heroku deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - run: |
          yarn plugin import workspace-tools
          yarn workspaces focus @solve/server
      - uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          app_dir: packages/server
