name: 'Deploy'

on:
  release:
    types:
      - published
  push:
    branches:
      - dev/deploy-to-heroku
  workflow_dispatch:

jobs:
  surge:
    name: Surge deployment
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to foo-bar.surge.sh
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      - run: yarn workspace @solve/client install
      - run: yarn workspace @solve/client build:web
      - run: yarn surge packages/client/web-build ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
